name: lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.2
      - name: Lint
        run: make ci-lint
