name: lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.2
      - name: Lint
        run: make ci-lint

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #           submodules: recursive
  #     - uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.14.2
  #     - name: Lint
  #       run: make ci-lint
  #     - name: Install protoc
  #       run: |
  #         PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip
  #         curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/$PROTOC_ZIP
  #         sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
  #         sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
  #         rm -f $PROTOC_ZIP
  #     - name: Install protoc-gen-go
  #       run: go get -u github.com/golang/protobuf/protoc-gen-go
  #     - name: Build Artifact
  #       run: make gen-proto-all
  #     - uses: technote-space/get-diff-action@v2
  #       id: protogen_diff
  #       with:
  #         PREFIX_FILTER: |
  #           protogen
  #         SUFFIX_FILTER: .pb.go
